[
  "Apa yang dimaksud dengan dinamika penduduk?",
  "Berikan contoh dari dinamika penduduk berdasarkan gambar data berikut!",
  "Apa yang dimaksud dengan kepadatan penduduk?",
  "Jumlah penduduk India pada tahun 2017 adalah 1,352,086,000 jiwa, sementara luas wilayahnya adalah 3,287,263 km2. Berapa jumlah kepadatan penduduk India pada tahun 2017?",
  "Jumlah penduduk Singapura pada tahun 2022 adalah 5,534,000 jiwa, sementara luas wilayahnya adalah 733 km2. Berapa jumlah kepadatan penduduk Singapura pada tahun 2022?",
  "Berdasarkan soal pada no 4 dan 5, Negara mana yang memiliki kepadatan penduduk lebih tinggi? Mengapa?",
  "Ada 3 hal yang menyebabkan perubahan jumlah penduduk, sebutkan!",
  "Pada tahun 2010, jumlah kelahiran di daerah A adalah 50,000 jiwa, sementara populasinya ada 10,000,000 jiwa. Berapakah angka kelahiran kasar di daerah A?",
  "Pada tahun 2010, jumlah kematian di daerah A adalah 20,000 jiwa, sementara populasinya ada 10,000,000 jiwa. Berapakah angka kematian kasar di daerah A?",
  "Pada tahun 2010, jumlah penduduk yang pergi dari daerah A adalah 70,000 jiwa, sementara populasinya ada 10,000,000 jiwa. Berapakah angka migrasi yang keluar dari daerah A?",
  "Pada tahun 2010, jumlah penduduk yang datang ke daerah A adalah 30,000 jiwa, sementara populasinya ada 10,000,000 jiwa. Berapakah angka migrasi yang masuk ke daerah A?",
  "Berdasarkan data di soal no 7, 9, 10, 11, berapakah pertumbuhan populasi dari daerah A?",
  "Apakah faktor yang mendorong naik dan turunnya angka kelahiran di suatu daerah?",
  "Apakah faktor yang mendorong naik dan turunnya angka kematian di suatu daerah?",
  "Migrasi atau perpindahan penduduk dibagi menjadi migrasi internasional dan migrasi internal. Jelaskan jenis dari migrasi internasional beserta contohnya, serta jelaskan jenis dari migrasi internal beserta contohnya!",
  "Jelaskan definisi dari piramida penduduk!",
  "Jelaskan apa yang dimaksud dengan piramida penduduk ekspansif! Golongan penduduk mana yang paling banyak, dan paling sedikit?",
  "Jelaskan apa yang dimaksud dengan piramida penduduk stasioner! Golongan penduduk mana yang paling banyak, dan paling sedikit?",
  "Jelaskan apa yang dimaksud dengan piramida penduduk konstruktif! Golongan penduduk mana yang paling banyak, dan paling sedikit?",
  "Apa yang dimaksud dengan komposisi penduduk?",
  "Ada yang dinamakan komposisi penduduk secara biologis, jelaskan dengan contoh!",
  "Ada yang dinamakan komposisi penduduk secara budaya, jelaskan dengan contoh!",
  "Ada yang dinamakan komposisi penduduk secara ekonomi, jelaskan dengan contoh!",
  "Jelaskan apa hubungan antara pertumbuhan penduduk yang besar dengan kualitas hidup masyarakat!",
  "Apa dampak yang bisa terjadi bila terjadi ledakan penduduk?",
  "Apa dampak yang bisa terjadi bila terjadi distribusi penduduk yang tidak merata?",
  "Apa dampak negatif dari dinamika penduduk yang berhubungan dengan lingkungan?",
  "Apa dampak negatif dari dinamika penduduk yang berhubungan dengan komposisi penduduk?",
  "Apa saja langkah yang bisa dilakukan pemerintah untuk mengatasi masalah dinamika penduduk?",
  "Apa kesimpulan yang bisa kamu dapatkan dari materi dinamika penduduk?"
]
